### ISSUE TITLE
Can't open a pickled file

### ISSUE THREAD

**Issue by keunwoochoi** [bmcfee/ismir2017_chords#2]
In short, tested on MacOS w/ python2.7 and 3.4, on Linux w/ python 2.7, and can't open it.

When I tried to open this: `/data/model_deep_aug/fold00_weights.pkl` I got...
```
UnpicklingError: invalid load key, 'H'.
```

```
$ python3
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  5 2014, 20:42:22)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> a = pickle.load(open('fold00_weights.pkl', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.UnpicklingError: invalid load key, 'H'.
```

Seems like there are many reasons that cause this problem. I tried few random solutions which didn't work. Do you have any idea?

**Comment by bmcfee** [comment]
I think the problem is that it's actually an h5 file with a .pkl extension.

**Comment by keunwoochoi** [comment]
Ohh.. gotcha, it is. Thanks.

**Comment by bmcfee** [comment]
Sorry about that!
