### ISSUE TITLE
Confused by  the "synthetic data" in your Data Pump code 

### ISSUE THREAD

**Issue by cloudscapes** [bmcfee/ismir2017_chords#4]
Hi dear Brian, 

I'm a bit confused by the " Synthetic Data" in your 01 - Data pump.ipynb file. If I'm not mistaken, in your 00 - Augmentation.ipynb file you have a separate directory for the audio files and another one for the corresponding annotations. In the 01 - Data pump.ipynb file you build two separate pumps, one for the original audio files and their annotations and one for the augmented audio files and their annotations and transform and save each of those two separately. But after that, there is a code snippet that deals with synthetic data that lies in a completely different folder! 

Are these " synthetic data" midi-synthesized audio files ?? I assume I won't need them and having the audio files and their annotations is enough to keep me going? 

Thanks in advance and with best regards, 

H.F

**Comment by bmcfee** [comment]
>  But after that, there is a code snippet that deals with synthetic data that lies in a completely different folder!
> 
> Are these " synthetic data" midi-synthesized audio files ?? I assume I won't need them and having the audio files and their annotations is enough to keep me going?

Good catch!  This is a hold-over from some earlier experiments with synthetic chord templates (not even midi files) that we were trying to use to train the decoder.  This didn't make it into the final version of the paper, and it's safe to ignore this bit.

**Comment by cloudscapes** [comment]
Thank you very much!
